# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff71937f772c96e4ea068d6c967c1dd2a0816dc4c738a748fd098dec464f2c39c602fb226561f3dd7b9e5708fda9fd16e4584bed1e8792f7065ca1cc1817e9f

test:
  secret_key_base: 7bdcb30e00453ed724ba299429ebe58abfe348fd795367ed6658006ce2d20da984f13b49947647f3f0a4d0f1f2075c34d04bdc1b120b6c71e69a365790f991d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
